apiVersion: v1
kind: Service
metadata:
  name: lti-launch-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: lti-launch
      protocol: TCP
      port: 5000
      targetPort: 5000
